lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path(
        "",
        views.DescriptionTemplateView.as_view(),
        name="main",
    ),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"
urlpatterns = [
    path(
        "",
        views.HomeView.as_view(),
        name="main",
    ),
    path(
        "coffee/",
        views.CoffeeView.as_view(),
        name="coffee",
    ),
    path(
        "echo/",
        views.EchoFormView.as_view(),
        name="echo",
    ),
    path(
        "echo/submit/",
        views.EchoFormView.as_view(),
        name="echo_submit",
    ),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path


urlpatterns = [
    path(
        "",
        include(("homepage.urls")),
        name="homepage",
    ),
    path(
        "about/",
        include(("about.urls")),
        name="about",
    ),
    path(
        "catalog/",
        include(("catalog.urls")),
        name="catalog",
    ),
    path(
        "feedback/",
        include(("feedback.urls")),
        name="feedback",
    ),
    path(
        "auth/",
        include(("users.urls")),
        name="users",
    ),
    path(
        "download/",
        include(("download.urls")),
        name="download",
    ),
    path(
        "statistic/",
        include(("statistic.urls")),
        name="statistic",
    ),
    path(
        "rating/",
        include(("rating.urls")),
        name="rating",
    ),
    path(
        "admin/",
        admin.site.urls,
        name="admin",
    ),
    path(
        "tinymce/",
        include("tinymce.urls"),
    ),
    path(
        "i18n/",
        include("django.conf.urls.i18n"),
    ),
    path(
        "auth/",
        django.urls.include(django.contrib.auth.urls),
    ),
]

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)
    if settings.MEDIA_ROOT:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )

lyceum/users/urls.py
from django.contrib.auth import views
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.urls import path, reverse_lazy

import users.forms
import users.views

__all__ = []


app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            authentication_form=users.forms.custom_auth_form(
                AuthenticationForm,
            ),
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            form_class=users.forms.custom_auth_form(
                PasswordChangeForm,
            ),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            form_class=users.forms.custom_auth_form(
                PasswordResetForm,
            ),
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            form_class=users.forms.custom_auth_form(
                SetPasswordForm,
            ),
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "signup/",
        users.views.SignupFormView.as_view(),
        name="signup",
    ),
    path(
        "activate/<username>/",
        users.views.ActivateRedirectView.as_view(),
        name="activate",
    ),
    path(
        "user_list/",
        users.views.UserListView.as_view(),
        name="user_list",
    ),
    path(
        "<int:pk>/",
        users.views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "profile/",
        users.views.ProfileUpdateView.as_view(),
        name="profile",
    ),
]

lyceum/users/models.py
from pathlib import Path
import sys
import uuid

from django.conf import settings
from django.contrib.auth import get_user_model
import django.db

import users.validators


__all__ = []

USER_MODEL = get_user_model()

if "makemigrations" not in sys.argv and "migrate" not in sys.argv:
    USER_MODEL._meta.get_field("email")._unique = True


def get_path_image(instance, filename):
    ext = Path(filename).suffix
    return f"users/{uuid.uuid4()}{ext}"


class Profile(django.db.models.Model):
    user = django.db.models.OneToOneField(
        settings.AUTH_USER_MODEL,
        verbose_name="пользователь",
        help_text="укажите пользователя",
        related_name="profile",
        related_query_name="profile",
        on_delete=django.db.models.CASCADE,
    )
    birthday = django.db.models.DateField(
        "дата рождения",
        help_text="укажите дату рождения",
        validators=[users.validators.birthday_validator],
        null=True,
        blank=True,
    )
    image = django.db.models.ImageField(
        "аватарка",
        help_text="загрузите автарку",
        upload_to=get_path_image,
        null=True,
        blank=True,
    )
    coffee_count = django.db.models.PositiveIntegerField(
        "количество переходов по /coffee/",
        help_text="сколько раз пользователь пытался сварить кофе",
        default=0,
    )
    attempts_count = django.db.models.PositiveIntegerField(
        default=0,
        verbose_name="количество попыток входа",
    )
    deactivation_date = django.db.models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="дата деактивации аккаунта",
    )

    def __str__(self):
        return f"Профиль пользователя {self.user.username}"

    class Meta:
        verbose_name = "дополнительное поле пользователя"
        verbose_name_plural = "дополнительные поля пользователей"


class UserProxyManager(django.contrib.auth.models.UserManager):
    CONONICAL_DOMAINS = {
        "yandex.ru": "ya.ru",
    }
    DOTS = {
        "ya.ry": "-",
        "gmail.com": "",
    }

    @classmethod
    def normalize_email(cls, email):
        email = super().normalize_email(email).lower()
        try:
            email_name, domain_part = email.rsplit("@", 1)
            email_name, *_ = email_name.split("+", 1)
            domain_part = cls.CONONICAL_DOMAINS.get(domain_part, domain_part)
            email_name = email_name.replace(
                ".",
                cls.DOTS.get(domain_part, "."),
            )
        except ValueError:
            pass
        else:
            email = f"{email_name}@{domain_part}"

        return email

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .select_related(
                USER_MODEL.profile.related.name,
            )
        )

    def active(self):
        return (
            self.get_queryset().filter(
                is_active=True,
            )
        ).only(
            USER_MODEL.username.field.name,
            USER_MODEL.is_superuser.field.name,
            USER_MODEL.first_name.field.name,
            USER_MODEL.last_name.field.name,
            USER_MODEL.email.field.name,
            f"{USER_MODEL.profile.related.name}__{Profile.image.field.name}",
            f"{USER_MODEL.profile.related.name}__"
            f"{Profile.birthday.field.name}",
            f"{USER_MODEL.profile.related.name}__"
            f"{Profile.coffee_count.field.name}",
        )

    def user_list(self):
        return (
            super()
            .get_queryset()
            .filter(
                is_active=True,
            )
        ).only(
            USER_MODEL.username.field.name,
        )

    def by_mail(self, email):
        return self.get_queryset().get(email=self.normalize_email(email))


class User(get_user_model()):
    objects = UserProxyManager()

    class Meta:
        proxy = True

lyceum/users/forms.py
from betterforms.multiform import MultiModelForm
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
import django.forms

import users.models

__all__ = []


def custom_auth_form(form):
    class CustomForm(form):
        def __init__(self, *args, **kwargs) -> None:
            super().__init__(*args, **kwargs)
            for field in self.visible_fields():
                field.field.widget.attrs["class"] = "form-control"

    return CustomForm


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta(UserCreationForm.Meta):
        model = users.models.User
        fields = (
            model.username.field.name,
            model.email.field.name,
        )


class CustomUserChangeForm(UserChangeForm):
    password = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta(UserChangeForm.Meta):
        fields = (
            users.models.User.email.field.name,
            users.models.User.username.field.name,
            users.models.User.first_name.field.name,
            users.models.User.last_name.field.name,
        )


class ProfileForm(django.forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        field_name = users.models.Profile.coffee_count.field.name
        self.fields[field_name].disabled = True
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = users.models.Profile
        fields = [
            model.birthday.field.name,
            model.image.field.name,
            model.coffee_count.field.name,
        ]


class UserProfileForm(MultiModelForm):
    form_classes = {
        "user": CustomUserChangeForm,
        "profile": ProfileForm,
    }

lyceum/users/views.py
import datetime

from django.conf import settings
import django.contrib
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
import django.forms
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
import django.views.generic

import users.forms
import users.models


__all__ = []


class SignupFormView(django.views.generic.FormView):
    form_class = users.forms.SignUpForm
    template_name = "users/signup.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = settings.DEFAULT_USER_IS_ACTIVE
        user.save()
        user.profile = users.models.Profile.objects.create(user_id=user.id)
        context_email = {
            "username": user.username,
        }
        send_mail(
            subject="Activate your account",
            message=render_to_string("users/signup_email.html", context_email),
            from_email=settings.EMAIL_HOST,
            recipient_list=[user.email],
        )
        django.contrib.messages.success(
            self.request,
            _("message_signup_success"),
        )
        return super().form_valid(form)


class ActivateRedirectView(django.views.generic.RedirectView):
    url = reverse_lazy("homepage:main")

    def get_redirect_url(self, *args, **kwargs):
        user = get_object_or_404(
            django.contrib.auth.get_user_model().objects,
            username=kwargs.get("username"),
        )
        if user.profile.attempts_count >= settings.MAX_AUTH_ATTEMPTS:
            time_limit = datetime.timedelta(days=7)
            start_date = user.profile.deactivation_date
        else:
            time_limit = datetime.timedelta(hours=12)
            start_date = user.date_joined

        if timezone.now() < start_date + time_limit:
            user.is_active = True
            user.save()
            user.profile.attempts_count = 0
            user.profile.save()
            django.contrib.messages.success(
                self.request,
                _("message_activate_success"),
            )
        else:
            django.contrib.messages.error(
                self.request,
                _("message_activate_error"),
            )

        return super().get_redirect_url(*args, **kwargs)


class UserListView(django.views.generic.ListView):
    template_name = "users/user_list.html"
    context_object_name = "users"
    queryset = users.models.User.objects.user_list()
    paginate_by = 100


class UserDetailView(django.views.generic.DetailView):
    template_name = "users/user_detail.html"
    context_object_name = "user_item"
    queryset = users.models.User.objects.active()


class ProfileUpdateView(LoginRequiredMixin, django.views.generic.UpdateView):
    template_name = "users/profile.html"
    form_class = users.forms.UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

    def get_form_kwargs(self):
        kwargs = super(ProfileUpdateView, self).get_form_kwargs()
        kwargs.update(
            instance={
                "user": self.object,
                "profile": self.object.profile,
            },
        )
        return kwargs

    def get_form(self, form_class=None):
        this_year = datetime.date.today().year
        year_range = range(this_year - 100, this_year + 1)
        form = super(ProfileUpdateView, self).get_form(form_class)
        form.forms["profile"].fields["birthday"].widget = (
            django.forms.SelectDateWidget(
                years=year_range,
                attrs={"class": "form-control"},
            )
        )
        return form

    def get_success_url(self):
        django.contrib.messages.success(
            self.request,
            _("message_profile_save_success"),
        )
        return super().get_success_url()

lyceum/templates/users/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "login_title"|capfirst %}
{% endblock title %}


{% block content %}
  {% if messages %}
    {% for message in messages %}
      {% if  message.tags == "error" %}
      <div class="alert alert-danger" role="alert">
      {% else %}
      <div class="alert alert-success" role="alert">
      {% endif %}
      {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-7">
      <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" with be_button=True form=form %}
        <a href="{% url "users:password_reset" %}">{% trans "forgot_password"|capfirst %}</a>
        <a href="{% url "users:signup" %}">{% trans "no_account"|capfirst %}</a>
      </form>
    </div>
  </div>
{% endblock content %}

lyceum/templates/users/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "success"|capfirst %}
{% endblock title %}


{% block content %}
<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">{% trans "logout_text" %}</h1>
      <p><a class="btn btn-primary btn-lg" href="{% url 'homepage:main' %}" role="button">{% trans "home"|capfirst %} &raquo;</a></p>
    </div>
</div>
{% endblock content %}

lyceum/templates/users/password_change.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "password_change_title"|capfirst %}
{% endblock title %}


{% block content %}
  <div class="row justify-content-center">
      <div class="col-12 col-md-6 col-lg-7">
        <form method="post">
          {% csrf_token %}
          {% include "includes/form.html" with be_button=True form=form %}
        </form>
      </div>
  </div>
{% endblock content %}

lyceum/templates/users/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "success"|capfirst %}
{% endblock title %}


{% block content %}
<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">{% trans "password_change_done_text"|capfirst %}</h1>
      <p><a class="btn btn-primary btn-lg" href="{% url 'homepage:main' %}" role="button">{% trans "home"|capfirst %} &raquo;</a></p>
    </div>
</div>
{% endblock content %}

lyceum/templates/users/password_reset.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "reset_title"|capfirst %}
{% endblock title %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-12 col-md-6 col-lg-7">
      <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" with be_button=True form=form %}
      </form>
  </div>
</div>
{% endblock content %}

lyceum/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "success"|capfirst %}
{% endblock title %}

{% block content %}
  <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">{% trans "password_reset_complite_text"|capfirst %}</h1>
        <p><a class="btn btn-primary btn-lg" href="{% url 'homepage:main' %}" role="button">{% trans "home"|capfirst %} &raquo;</a></p>
      </div>
  </div>
{% endblock content %}

lyceum/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "reset_title"|capfirst %}
{% endblock title %}


{% block content %}
<div class="row justify-content-center">
  <div class="col-12 col-md-6 col-lg-7">
      <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" with be_button=True form=form %}
      </form>
  </div>
</div>
{% endblock content %}

lyceum/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "success"|capfirst %}
{% endblock title %}

{% block content %}
<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">{% trans "password_reset_done_text"|capfirst %}</h1>
      <p><a class="btn btn-primary btn-lg" href="{% url 'homepage:main' %}" role="button">{% trans "home"|capfirst %} &raquo;</a></p>
    </div>
</div>
{% endblock content %}

lyceum/templates/users/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}


{% block title %}
{% trans "profile_title"|capfirst %}: {{ user.username }}
{% endblock %}


{% block content %}
{% if messages %}
  {% for message in messages %}
    {% if  message.tags == "error" %}
    <div class="alert alert-danger" role="alert">
    {% else %}
    <div class="alert alert-success" role="alert">
    {% endif %}
    {{ message }}
    </div>
  {% endfor %}
{% endif %}
<h1>{{ user.username }}</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% include "includes/form.html" with be_button=True form=form %}
  <a href="{% url "homepage:coffee" %}">{% trans "glass_of_coffee" %}</a>
  <a href="{% url "users:password_change" %}">{% trans "password_change_title" %}</a>
</form>
{% endblock content %}

lyceum/templates/users/signup.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "login_title"|capfirst %}
{% endblock title %}


{% block content %}
<div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-7">
      <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" with be_button=True form=form %}
      </form>
    </div>
</div>
{% endblock content %}

lyceum/templates/users/signup_email.html
{% load i18n %}{% autoescape off %}
{% trans "activate_email_title" %}

{% trans "activate_email_text" %}
{% block reset_link %}
http://127.0.0.1:8000{% url 'users:activate' username %}
{% endblock %}
{% endautoescape %}

lyceum/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}

{% block title %}
{% trans "user_detail_title"|capfirst %}
{% endblock title %}

{% block content %}
<div class="container py-5">
  <div class="row">
    <div class="col-lg-4">
      <div class="card mb-4">
        <div class="card-body text-center">
          {% thumbnail user_item.profile.image "150x160" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="rounded-circle img-fluid" alt="">
          {% endthumbnail %}
          <h5 class="my-3">{{ user_item.username }}</h5>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="card mb-4">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">{% trans "name"|capfirst %}</p>
            </div>
            <div class="col-sm-9">
              {% if user_item.first_name %}
                <p class="text-muted mb-0">{{ user_item.first_name }}</p>
                {% else %}
                <p  style="font-style: italic;" class="text-muted mb-0">{% trans "not_indicated" %}</p>
              {% endif %}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">{% trans "last_name"|capfirst %}</p>
            </div>
            <div class="col-sm-9">
              {% if user_item.first_name %}
                <p class="text-muted mb-0">{{ user_item.last_name }}</p>
                {% else %}
                <p style="font-style: italic;" class="text-muted mb-0">{% trans "not_indicated" %}</p>
              {% endif %}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">{% trans "mail"|capfirst %}</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ user_item.email }}</p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">{% trans "birthday"|capfirst %}</p>
            </div>
            <div class="col-sm-9">
              {% if user_item.profile.birthday %}
                <p class="text-muted mb-0">{{ user_item.profile.birthday }}</p>
              {% else %}
                <p style="font-style: italic;" class="text-muted mb-0">{% trans "not_indicated" %}</p>
              {% endif %}
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <p class="mb-0">{% trans "count_drink_coffee"|capfirst %}</p>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">{{ user_item.profile.coffee_count }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

lyceum/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}


{% block title %}
{% trans "user_list_title"|capfirst %}
{% endblock title %}

{% block content %}
  <h1>{% trans "user_list_title"|capfirst %}</h1>
  <hr>
  {% for user in users %}
    <a href={% url "users:user_detail" user.id %}><p>
      <div class="card">
          <div class="card-body">
              {{ user.username }}
          </div>
      </div>
    </p></a>
  {% empty %}
    <h1 class="pb-2 mb-0">{% trans "empty" %}</h1>
  {% endfor %}
{% endblock content %}