lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path(
        "",
        views.DescriptionTemplateView.as_view(),
        name="main",
    ),
]

lyceum/catalog/urls.py
from django.urls import path, re_path, register_converter

from catalog import converters, views


register_converter(converters.PositiveIntegerConverter, "pint")
app_name = "catalog"

urlpatterns = [
    path(
        "",
        views.ItemListView.as_view(),
        name="main",
    ),
    path(
        "<int:pk>/",
        views.ItemDetailView.as_view(),
        name="item_detail",
    ),
    re_path(
        r"^re/(?P<pk>[1-9]\d*)/",
        views.ItemDetailView.as_view(),
        name="re",
    ),
    path(
        "converter/<pint:pk>/",
        views.ItemDetailView.as_view(),
        name="converter",
    ),
    path(
        "new/",
        views.ItemNewListView.as_view(),
        name="new",
    ),
    path(
        "friday/",
        views.ItemFridayListView.as_view(),
        name="friday",
    ),
    path(
        "unverified/",
        views.ItemUnverifiedListView.as_view(),
        name="unverified",
    ),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"
urlpatterns = [
    path(
        "",
        views.HomeView.as_view(),
        name="main",
    ),
    path(
        "coffee/",
        views.CoffeeView.as_view(),
        name="coffee",
    ),
    path(
        "echo/",
        views.EchoFormView.as_view(),
        name="echo",
    ),
    path(
        "echo/submit/",
        views.EchoFormView.as_view(),
        name="echo_submit",
    ),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path


urlpatterns = [
    path(
        "",
        include(("homepage.urls")),
        name="homepage",
    ),
    path(
        "about/",
        include(("about.urls")),
        name="about",
    ),
    path(
        "catalog/",
        include(("catalog.urls")),
        name="catalog",
    ),
    path(
        "feedback/",
        include(("feedback.urls")),
        name="feedback",
    ),
    path(
        "auth/",
        include(("users.urls")),
        name="users",
    ),
    path(
        "download/",
        include(("download.urls")),
        name="download",
    ),
    path(
        "statistic/",
        include(("statistic.urls")),
        name="statistic",
    ),
    path(
        "rating/",
        include(("rating.urls")),
        name="rating",
    ),
    path(
        "admin/",
        admin.site.urls,
        name="admin",
    ),
    path(
        "tinymce/",
        include("tinymce.urls"),
    ),
    path(
        "i18n/",
        include("django.conf.urls.i18n"),
    ),
    path(
        "auth/",
        django.urls.include(django.contrib.auth.urls),
    ),
]

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)
    if settings.MEDIA_ROOT:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )

lyceum/users/urls.py
from django.contrib.auth import views
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.urls import path, reverse_lazy

import users.forms
import users.views

__all__ = []


app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            authentication_form=users.forms.custom_auth_form(
                AuthenticationForm,
            ),
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            form_class=users.forms.custom_auth_form(
                PasswordChangeForm,
            ),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            form_class=users.forms.custom_auth_form(
                PasswordResetForm,
            ),
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            form_class=users.forms.custom_auth_form(
                SetPasswordForm,
            ),
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "signup/",
        users.views.SignupFormView.as_view(),
        name="signup",
    ),
    path(
        "activate/<username>/",
        users.views.ActivateRedirectView.as_view(),
        name="activate",
    ),
    path(
        "user_list/",
        users.views.UserListView.as_view(),
        name="user_list",
    ),
    path(
        "<int:pk>/",
        users.views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "profile/",
        users.views.ProfileUpdateView.as_view(),
        name="profile",
    ),
]

lyceum/templates/includes/footer.html
{% load i18n %}
{% load static %}


<script defer src="{% static 'js/footer/client_actual_year.js' %}" ></script>
<footer class="border-top text-center py-3">
  <p id="curryear">© {% now 'Y-m-d H:i:s:ms\Z' %}</p>
  <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select class="btn btn-mini" name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
          <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
            {{ language.name_local }} ({{ language.code }})
          </option>
        {% endfor %}
    </select>
    <input class="mt-auto btn btn-md btn-block btn-primary" type="submit" value={% trans "go"|capfirst %}>
  </form>
</footer>

lyceum/templates/includes/form.html
{% load i18n %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}
  
{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
  {% for error in form.non_field_errors %}
    <div>{{ error }}</div>
  {% endfor %}
  </div>
{% endif %}
  
{% for field in form.visible_fields %}
  <div class="mb-3 {% if field.widget_type == 'checkbox' %}form-check{% endif %}">
  <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>

  {{ field }}

  {% if form.is_bound and field.errors %}
    {% for error in field.errors %}
      <div class="invalid-feedback d-block">
        {{ error }}
      </div>
    {% endfor %}
  {% endif %}

  {% if field.help_text %}
    <div class="form-text">{{ field.help_text }}</div>
  {% endif %}
  </div>
{% endfor %}


{% if be_button %}
<button type="submit" class="btn btn-primary">{% if submit_text %}{{submit_text}}{% else %}{% trans "submit" %}{% endif %}</button>
{% endif %}

lyceum/templates/includes/header.html
{% load static %}
{% load i18n %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e9ecef">
    <div class="container">
      <a class="navbar-brand" href="{% url 'homepage:main' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        {% trans "brand_name"|capfirst %}
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% with request.resolver_match.view_name as view_name %}
      <div class="collapse navbar-collapse multi-collapse justify-content-end" id="navbarNav">
        <ul class="nav navbar-nav">
          <li class="nav-item navbar-brand">
            <a class="nav-link {% if view_name == 'homepage:main' %}active{% endif %}" href="{% url 'homepage:main' %}">
              {% trans "home"|capfirst %}
            </a>
          </li>
          <li class="nav-item navbar-brand">
            <a class="nav-link {% if view_name == 'about:main' %}active{% endif %}" href="{% url 'about:main' %}">
              {% trans "about_title"|capfirst %}
            </a>
          </li>
          <li class="nav-item navbar-brand">
            <a class="nav-link {% if view_name in 'catalog:maincatalog:newcatalog:fridaycatalog:unverified' %}active{% endif %}" href="{% url 'catalog:main' %}">
              {% trans "item_list_title"|capfirst %}
            </a>
          </li>
          <li class="nav-item navbar-brand">
            <a class="nav-link {% if view_name == 'feedback:feedback' %}active{% endif %}" href="{% url 'feedback:feedback' %}">
              {% trans "feedback_title"|capfirst %}
            </a>
          </li>
          <li class="nav-item navbar-brand">
            <a class="nav-link" href="{% url 'users:user_list' %}">
              {% trans "user_list_title"|capfirst %}
            </a>
          </li>
          {% if user.is_authenticated %}
            {% if user.is_superuser %}
              <li class="nav-item navbar-brand">
                <a class="nav-link" href="{% url 'admin:index' %}">
                  {% trans "admin_title"|capfirst %}
                </a>
              </li>
            {% endif %}
            <li class="nav-item navbar-brand">
              <a class="nav-link {% if view_name == 'users:profile' %}active{% endif %}" href="{% url 'users:profile' %}">
                {% trans "profile_title"|capfirst %}
              </a>
            </li>
            <li class="nav-item navbar-brand">
              <a class="nav-link {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">
                {% trans "logout_title"|capfirst %}
              </a>
            </li>
            <li class="nav-item navbar-brand">
              <a class="nav-link {% if view_name == 'statistic:by-user:graded-items:by-items' %}active{% endif %}" href="{% url 'statistic:by-user' %}">
                {% trans "statistics"|capfirst %}
              </a>
            </li>
            {% else %}
              <li class="nav-item navbar-brand">
                <a class="nav-link {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">
                  {% trans "login_title"|capfirst %}
                </a>
              </li>
          {% endif %}
        </ul>
      </div>
      {% endwith %}
    </div>
  </nav>
  {% if birthdays  %}
    <div class="container mt-3">
      <div class="container-fluid">
        <div class="row flex-nowrap" style="overflow-x: scroll;">
          {% for elem in birthdays %}
            <div class="col-2 px-0 pm-1 text-center">
                <div class="card card-block">{{ elem.username }} {{ elem.email }}</div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}

</header>

lyceum/templates/includes/item_card.html
{% load static %}
{% load i18n %}
<div class="col-6 col-md-4 my-1 d-flex align-items-stretch">
  <div class="card">
    <img
      class="img-fluid card-img-top"
      {% if item.main_image %}
        src="{{ item.main_image.get_image_413x413.url }}"
      {% else %}
        src="{% static 'img/image-holder.png' %}"
      {% endif %}
      alt="{% trans 'item_image'|capfirst %}"
    >
    <div class="card-body d-flex flex-column">
      <h5 class="card-title">{{ item.name }}</h5>
      <div class="border mb-3 rounded">
        <div class="card-header">
          {% trans "category"|capfirst %}
        </div>
        <ul class="list-group list-group-flush rounded">
          <li class="list-group-item">{{ item.category.name }}</li>
        </ul>
      </div>
      <div class="border mb-3 rounded">
        <div class="card-header">
          {% trans "description"|capfirst %}
        </div>
        <ul class="list-group list-group-flush rounded">
            <li class="list-group-item">{{ item.text|safe|truncatewords_html:10 }}</li>
        </ul>
      </div>
      <div class="border mb-3 rounded">
        <div class="card-header">
          {% trans "tags"|capfirst %}
        </div>
        <ul class="list-group list-group-flush">
          {% for tag in item.tags.all %}
            {% if forloop.last %}
              <li class="list-group-item rounded-bottom">{{ tag.name }}</li>
            {% else %}
              <li class="list-group-item">{{ tag.name }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
      {% if items %}
      
      {% endif %}
      <a href={% url 'catalog:item_detail' pk=item.id %} class="mt-auto btn btn-md btn-block btn-primary">{% trans "more_details"|capfirst %}</a>
    </div>
  </div>
</div>

lyceum/templates/includes/statistic_item_card.html
{% load static %}
{% load i18n %}
{% trans "nobody" as nobody %}
<div class="col-6 col-md-4 my-1 d-flex align-items-stretch">
  <div class="card">
    <img
      class="img-fluid card-img-top"
      {% if item.main_image %}
        src="{{ item.main_image.get_image_413x413.url }}"
      {% else %}
        src="{% static 'img/image-holder.png' %}"
      {% endif %}
      alt="{% trans 'item_image'|capfirst %}"
    >
    <div class="card-body d-flex flex-column">
      <h5 class="card-title">{{ item.name }}</h5>
      <div class="border mb-3 rounded">
        <div class="card-header">
          {% trans "grade_count"|capfirst %}
        </div>
        <ul class="list-group list-group-flush rounded">
          <li class="list-group-item">{{ item.count_grades|default:0 }}</li>
        </ul>
      </div>
      <div class="border mb-3 rounded">
        <div class="card-header">
          {% trans "rating"|capfirst %}
        </div>
        <ul class="list-group list-group-flush rounded">
          <li class="list-group-item">{{ item.avg_grades|floatformat|default:0 }}</li>
        </ul>
      </div>
      <div class="border mb-3 rounded">
        <div class="card-header">
          {% trans "max_user_grade"|capfirst %}
        </div>
        <ul class="list-group list-group-flush rounded">
          <li class="list-group-item">{{ item.love|default:nobody|truncatechars:15 }}</li>
        </ul>
      </div>
      <div class="border mb-3 rounded">
        <div class="card-header">
          {% trans "min_user_grade"|capfirst %}
        </div>
        <ul class="list-group list-group-flush rounded">
          <li class="list-group-item">{{ item.hate|default:nobody|truncatechars:15 }}</li>
        </ul>
      </div>
      <a href={% url 'catalog:item_detail' pk=item.id %} class="mt-auto btn btn-md btn-block btn-primary">{% trans "more_details"|capfirst %}</a>
    </div>
  </div>
</div>