lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path(
        "",
        views.DescriptionTemplateView.as_view(),
        name="main",
    ),
]

lyceum/catalog/urls.py
from django.urls import path, re_path, register_converter

from catalog import converters, views


register_converter(converters.PositiveIntegerConverter, "pint")
app_name = "catalog"

urlpatterns = [
    path(
        "",
        views.ItemListView.as_view(),
        name="main",
    ),
    path(
        "<int:pk>/",
        views.ItemDetailView.as_view(),
        name="item_detail",
    ),
    re_path(
        r"^re/(?P<pk>[1-9]\d*)/",
        views.ItemDetailView.as_view(),
        name="re",
    ),
    path(
        "converter/<pint:pk>/",
        views.ItemDetailView.as_view(),
        name="converter",
    ),
    path(
        "new/",
        views.ItemNewListView.as_view(),
        name="new",
    ),
    path(
        "friday/",
        views.ItemFridayListView.as_view(),
        name="friday",
    ),
    path(
        "unverified/",
        views.ItemUnverifiedListView.as_view(),
        name="unverified",
    ),
]

lyceum/download/urls.py
from django.urls import path

from download import views


app_name = "download"
urlpatterns = [
    path(
        "<path:path>",
        views.DownloadView.as_view(),
        name="main",
    ),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path


urlpatterns = [
    path(
        "",
        include(("homepage.urls")),
        name="homepage",
    ),
    path(
        "about/",
        include(("about.urls")),
        name="about",
    ),
    path(
        "catalog/",
        include(("catalog.urls")),
        name="catalog",
    ),
    path(
        "feedback/",
        include(("feedback.urls")),
        name="feedback",
    ),
    path(
        "auth/",
        include(("users.urls")),
        name="users",
    ),
    path(
        "download/",
        include(("download.urls")),
        name="download",
    ),
    path(
        "statistic/",
        include(("statistic.urls")),
        name="statistic",
    ),
    path(
        "rating/",
        include(("rating.urls")),
        name="rating",
    ),
    path(
        "admin/",
        admin.site.urls,
        name="admin",
    ),
    path(
        "tinymce/",
        include("tinymce.urls"),
    ),
    path(
        "i18n/",
        include("django.conf.urls.i18n"),
    ),
    path(
        "auth/",
        django.urls.include(django.contrib.auth.urls),
    ),
]

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)
    if settings.MEDIA_ROOT:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )

lyceum/rating/urls.py
from django.urls import path

from rating import views

app_name = "rating"

urlpatterns = [
    path(
        "delete/<int:pk>/",
        views.DeleteRedirectView.as_view(),
        name="delete",
    ),
]

lyceum/catalog/models.py
import django.core.validators
import django.db
from django.utils import timezone
from slugify import slugify
import tinymce.models

from catalog.validators import ValidateMustContain
from core.models import AbstractModel, BaseImage


__all__ = []


class Round(django.db.models.Func):
    function = "ROUND"
    arity = 2


class Tag(AbstractModel):
    slug = django.db.models.SlugField(
        "слаг",
        max_length=200,
        unique=True,
        blank=True,
        help_text="строка идентификатор"
        "(заполните чтобы изменить автоматический слаг)",
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "тег"
        verbose_name_plural = "теги"


class Category(AbstractModel):
    slug = django.db.models.SlugField(
        "слаг",
        max_length=200,
        unique=True,
        blank=True,
        help_text="строка идентификатор"
        "(заполните чтобы изменить автоматический слаг)",
    )
    weight = django.db.models.IntegerField(
        "вес",
        default=100,
        validators=[
            django.core.validators.MaxValueValidator(32767),
            django.core.validators.MinValueValidator(1),
        ],
        help_text="ну какой вес то",
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class ItemManager(django.db.models.Manager):
    def published(self):
        queryset = (
            self.get_queryset()
            .filter(
                is_published=True,
                category__is_published=True,
            )
            .select_related(
                Item.category.field.name,
                Item.main_image.related.name,
            )
            .prefetch_related(
                django.db.models.Prefetch(
                    Item.tags.field.name,
                    queryset=Tag.objects.filter(is_published=True).only(
                        Tag.name.field.name,
                    ),
                ),
            )
        )
        return queryset.only(
            Item.name.field.name,
            f"{Item.category.field.name}__{Category.name.field.name}",
            Item.text.field.name,
            f"{Item.tags.field.name}__{Tag.name.field.name}",
            f"{Item.main_image.related.name}__"
            f"{ItemMainImage.image.field.name}",
        ).order_by(f"{Item.category.field.name}__{Category.name.field.name}")

    def on_main(self):

        return (
            self.published()
            .filter(is_on_main=True)
            .order_by(Item.name.field.name)
        )

    def get_item(self):
        queryset = (
            self.published()
            .prefetch_related(
                django.db.models.Prefetch(
                    Item.images.field.related_query_name(),
                    queryset=ItemSecondaryImage.objects.all(),
                ),
            )
            .annotate(
                rating=django.db.models.ExpressionWrapper(
                    Round(
                        django.db.models.Avg(
                            f"{Item.grades.field.related_query_name()}__"
                            f"{Item.grades.field.model.grade.field.name}",
                        ),
                        2,
                    ),
                    output_field=django.db.models.FloatField(),
                ),
                count_grade=django.db.models.Count(
                    Item.grades.field.related_query_name(),
                ),
            )
        )

        return queryset.only(
            Item.name.field.name,
            f"{Item.category.field.name}__{Category.name.field.name}",
            Item.text.field.name,
            f"{Item.tags.field.name}__{Tag.name.field.name}",
            f"{Item.main_image.related.name}__"
            f"{ItemMainImage.image.field.name}",
            f"{Item.images.field._related_name}__"
            f"{ItemSecondaryImage.image.field.name}",
        )


class Item(AbstractModel):
    objects = ItemManager()
    is_on_main = django.db.models.BooleanField(
        "в главном",
        default=False,
        help_text="находится на домашней странице",
    )
    text = tinymce.models.HTMLField(
        "текст",
        validators=[
            ValidateMustContain("превосходно", "роскошно"),
        ],
        help_text="опишите",
    )
    category = django.db.models.ForeignKey(
        Category,
        on_delete=django.db.models.CASCADE,
        verbose_name="категория",
        related_name="items",
        related_query_name="items",
        help_text="выберите категорию",
    )
    tags = django.db.models.ManyToManyField(
        Tag,
        verbose_name="теги",
        related_name="items",
        related_query_name="items",
        help_text="выберите теги",
    )
    created = django.db.models.DateTimeField(
        "создано",
        help_text="дата и время создания",
        auto_now_add=True,
        null=True,
    )
    updated = django.db.models.DateTimeField(
        "обновлено",
        help_text="дата и время обновления",
        editable=False,
        null=True,
    )

    def save(self, *args, **kwargs):
        if not self.updated:
            self.updated = self.created
        else:
            self.updated = timezone.now()

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"


class ItemMainImage(BaseImage):
    item = django.db.models.OneToOneField(
        Item,
        on_delete=django.db.models.CASCADE,
        verbose_name="товар",
        help_text="товар изображения",
        related_name="main_image",
        related_query_name="main_image",
    )

    class Meta:
        verbose_name = "главное изображение"
        verbose_name_plural = "главные изображения"


class ItemSecondaryImage(BaseImage):
    item = django.db.models.ForeignKey(
        Item,
        on_delete=django.db.models.CASCADE,
        verbose_name="товар",
        help_text="товар изображения",
        related_name="images",
        related_query_name="images",
    )

    class Meta:
        verbose_name = "дополнительное изображение"
        verbose_name_plural = "дополнительные изображения"

lyceum/catalog/views.py
import datetime
import random

from django.contrib.auth.decorators import login_required
import django.contrib.messages
from django.db.models import F
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
import django.views.generic

import catalog.models
import rating.forms
import rating.models

__all__ = []


class ItemListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    queryset = catalog.models.Item.objects.published()


class ItemDetailView(
    django.views.generic.edit.FormMixin,
    django.views.generic.DetailView,
):
    template = "catalog/item_detail.html"
    context_object_name = "item"
    queryset = catalog.models.Item.objects.get_item()
    model = rating.models.Grade
    form_class = rating.forms.GradeForm

    def get_success_url(self):
        django.contrib.messages.success(
            self.request,
            _("message_grade_save_success"),
            fail_silently=True,
        )
        return reverse("catalog:item_detail", kwargs={"pk": self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["chapter"] = _("item_list_title")
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemDetailView, self).get_form_kwargs()
        if self.request.user.is_authenticated:
            grade = self.object.grades.filter(
                user=self.request.user,
            ).first()
            kwargs.update(
                instance=grade,
            )

        return kwargs

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)

        return self.form_invalid(form)

    def form_valid(self, form):
        grade = form.save(commit=False)
        grade.user = self.request.user
        grade.item = self.object
        grade.save()
        return super().form_valid(form)


class ItemNewListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    model = catalog.models.Item

    def get_queryset(self):
        qs = self.model.objects.published()
        items = list(
            qs.filter(
                created__gt=timezone.now() - datetime.timedelta(hours=24 * 7),
            ).all(),
        )
        ln_items = len(items)
        return sorted(
            random.sample(items, 5 if ln_items >= 5 else ln_items),
            key=lambda item: item.category.name,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["chapter"] = _("new")
        return context


class ItemFridayListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    model = catalog.models.Item

    def get_queryset(self):
        qs = self.model.objects.published()
        item_category = catalog.models.Item.category.field.name
        category_name = catalog.models.Category.name.field.name
        return reversed(
            qs.filter(updated__week_day=6).order_by(
                f"-{item_category}__{category_name}",
            )[:5],
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["chapter"] = _("friday")
        return context


class ItemUnverifiedListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    model = catalog.models.Item

    def get_queryset(self):
        qs = self.model.objects.published()
        return qs.filter(updated=F("created"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["chapter"] = _("unverified")
        return context

lyceum/templates/catalog/item_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
{% trans "item_detail_title"|capfirst %}
{% endblock title %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      {% if  message.tags == "error" %}
      <div class="alert alert-danger" role="alert">
      {% else %}
      <div class="alert alert-success" role="alert">
      {% endif %}
      {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  <div class="d-flex flex-wrap justify-content-between">
    <h1 class="pb-2 mb-0">{{ item.name }}</h1>
    <h1 class="pb-2 mb-0">{% trans "grade_count"|capfirst %}: {{ item.count_grade }}</h1>
    <h1 class="pb-2 mb-0">{% trans "rating"|capfirst %}: {% if item.rating %}{{ item.rating|safe }}{% else %}{% trans "no_rating" %}{% endif %}</h1>
  </div>
  <div class="d-flex flex-wrap">
    {% for tag in item.tags.all %}
      <span class="badge bg-secondary ms-1">{{ tag.name }}</span>
    {% endfor %}
  </div>
  <div class="row mt-3 mb-3">
    <div class="col-12 col-md-6">
      <h2>{% trans "description"|capfirst %}</h2>
        {{ item.text|safe }}
    </div>
    <div class="col-12 col-md-6 mb-5">
      <div class="mw-413 mh-413 position-relative d-inline-block">
        <img
          class="img-fluid"
          {% if item.main_image %}
            src="{{ item.main_image.get_image_413x413.url }}"
          {% else %}
            src="{% static 'img/image-holder.png' %}"
            height=413
            width=413
          {% endif %}
          alt="{% trans 'item_image' %}"
        >
        {% if item.main_image %}
        <a href="{% url 'download:main' item.main_image.image.name %}" class="position-absolute top-0 end-0 btn btn-primary" download>
          <svg class="bi bi-download" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
            <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
            <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
          </svg>
        </a>
        {% endif %}
      </div>
    </div>
    {% if user.is_authenticated %}
      <form method="post">
        {% csrf_token %}
        {% include "includes/form.html" with be_button=True form=form %}
        {% if form.instance.id %}
          <a href="{% url "rating:delete" item.id %}" type="button" class="btn btn-danger">{% trans "delete" %}</a>
        {% endif %}
      </form>
    {% endif %}
  </div>
  <hr>
  <div class="d-flex flex-wrap">
    {% for image in  item.images.all %}
      <div class="col-12 col-md-1 mb-3">
        <div class="mw-108 mh-108 position-relative d-inline-block border border-black">
          <img
            class="img-fluid"
            src="{{ image.get_image_300x300.url }}"
            alt="{% trans 'item_image' %}"
          >
          <a href="{% url 'download:main' image.image.name %}" type="button" class="px-1 py-0 position-absolute top-0 end-0 btn btn-primary" download>
            <svg class="bi bi-download" width="16" height="12" fill="currentColor" viewBox="0 0 16 20">
              <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
              <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
            </svg>
          </a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

lyceum/templates/catalog/item_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
{% trans "item_list_title"|capfirst %}
{% endblock %}

{% block content %}
  <nav class="navbar">
    {% with request.resolver_match.view_name as view_name %}
    <ul class="pagination pagination-lg d-flex flex-wrap w-100">
      <li class="page-item col-6 col-md-3 {% if view_name == 'catalog:main' %}active{% endif %}">
        <a class="page-link fs-6" href="{% url 'catalog:main' %}" tabindex="-1">{% trans "item_list_title"|capfirst %}</a>
      </li>
      <li class="page-item col-6 col-md-3 {% if view_name == 'catalog:new' %}active{% endif %}">
        <a class="page-link fs-6" href="{% url 'catalog:new' %}">{% trans "new"|capfirst %}</a>
      </li>
      <li class="page-item col-6 col-md-3 {% if view_name == 'catalog:friday' %}active{% endif %}">
        <a class="page-link fs-6" href="{% url 'catalog:friday' %}">{% trans "friday"|capfirst %}</a>
      </li>
      <li class="page-item col-6 col-md-3 {% if view_name == 'catalog:unverified' %}active{% endif %}">
        <a class="page-link fs-6" href="{% url 'catalog:unverified' %}">{% trans "unverified"|capfirst %}</a>
      </li>
    </ul>
    {% endwith %}
  </nav>
  <h1 class="pb-2 mb-3">{{ chapter|capfirst }}</h1>
    {% for item in items %}
        {% ifchanged item.category.name %}
          {% if not forloop.first %}
            </div>
          {% endif %}
          <hr>
          <div class="card-header py-3">
            <h3 class="my-0 fw-bold text-center">{{ item.category.name }}</h3>
          </div>
          <hr>
          <div class="row">
        {% endifchanged %}
        {% include "includes/item_card.html" %}
        {% if forloop.last %}
          </div>
        {% endif %}
        {% empty %}
          <h1 class="pb-2 mb-0">{% trans "empty" %}</h1>
    {% endfor %}
{% endblock %}